project:
  type: book
  resources:
    - images/preview.png
    - assets/

highlight-style: github

book:
  title: "Open Source Typography"
  subtitle: "A Curated Interactive Lookbook"
  author: "Nan Xiao"
  description: |
    Discover open source typefaces for web and software projects.

  cover-image: "images/cover.png"
  image: "images/preview.png"
  favicon: "images/favicon.png"

  site-url: https://nanx.me/ost/
  repo-url: https://github.com/nanxstats/ost
  repo-actions: [edit, issue, source]
  sharing: [twitter, linkedin]
  reader-mode: true

  open-graph:
    image: https://nanx.me/ost/images/preview.png
    description: |
      Discover open source typefaces for web and software projects.
  twitter-card:
    image: https://nanx.me/ost/images/preview.png
    description: |
      Discover open source typefaces for web and software projects.
    card-style: summary_large_image
    creator: "@nanxstats"
    site: "@nanxstats"

  chapters:
    - index.qmd
    - preface.qmd

    - part: serif.qmd
      chapters:
        - besley.qmd
        - cardo.qmd
        - castoro.qmd
        - cormorant-garamond.qmd
        - crimson-pro.qmd
        - eb-garamond.qmd
        - et-book.qmd
        - ibm-plex-serif.qmd
        - libre-caslon-text.qmd
        - literata.qmd
        - lora.qmd
        - mlmodern.qmd
        - newsreader.qmd
        - roboto-serif.qmd
        - source-serif.qmd
        - stix-two-text.qmd
        - xcharter.qmd

    - part: sans-serif.qmd
      chapters:
        - albert-sans.qmd
        - aspekta.qmd
        - cabin.qmd
        - commissioner.qmd
        - dm-sans.qmd
        - figtree.qmd
        - fira-sans.qmd
        - hanken-grotesk.qmd
        - ibm-plex-sans.qmd
        - instrument-sans.qmd
        - inter.qmd
        - jost.qmd
        - mona-sans.qmd
        - nunito-sans.qmd
        - outfit.qmd
        - overused-grotesk.qmd
        - red-hat-text.qmd
        - sn-pro.qmd
        - source-sans.qmd
        - spartan-mb.qmd
        - special-gothic.qmd
        - spline-sans.qmd

    - part: slab-serif.qmd
      chapters:
        - roboto-slab.qmd
        - zilla-slab.qmd

    - part: monospace.qmd
      chapters:
        - cascadia-code.qmd
        - commit-mono.qmd
        - fira-code.qmd
        - fragment-mono.qmd
        - ibm-plex-mono.qmd
        - inconsolata.qmd
        - jetbrains-mono.qmd
        - red-hat-mono.qmd
        - roboto-mono.qmd
        - source-code-pro.qmd
        - spline-sans-mono.qmd

    - part: display.qmd
      chapters:
        - dm-serif-display.qmd
        - dm-serif-text.qmd
        - gloock.qmd
        - libre-caslon-display.qmd
        - red-hat-display.qmd

    - part: small-caps.qmd
      chapters:
        - alegreya-sans-sc.qmd
        - im-fell-french-canon-sc.qmd
        - spectral-sc.qmd

    - references.qmd

bibliography: references.bib

format:
  html:
    theme: [cosmo, custom.scss]
    mainfont: "BDO Grotesk, system-ui, -apple-system, Segoe UI, Roboto, Helvetica Neue, Noto Sans, Liberation Sans, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol, Noto Color Emoji"
